import 'package:flutter/material.dart';
import 'package:vtuberdex/Models/vtuber.dart';

class Vtubers with ChangeNotifier {
  List<Vtuber> vtubers = [
    Vtuber(
        name: "Melty",
        birthday: "Sept. 13",
        debut: "Febr. 13",
        country: "Chile",
        emotes: [
          "assets/emotes/melty/1.png",
          "assets/emotes/melty/2.png",
          "assets/emotes/melty/3.png",
          "assets/emotes/melty/4.png",
          "assets/emotes/melty/5.png",
        ],
        sounds: ["assets/sounds/melty/puto.mp3"],
        colors: [Color(0xff7663ED), Color.fromARGB(20, 69, 64, 224)],
        wallpapers: [],
        lore:
            "Hewwo~ soy Melty Me gustan mucho los juegos mmo/rpg y survival, me encanta divertirme jugando ya sea sola o en multijugador(en especial en multijugador).Tengo una fascinación por los anime de genero Isekai / Love Comedy, y las novelas ligeras.Sí, soy bastante Otaku",
        image: "assets/images/melty_grande.png",
        nameVtuber: "Memelty",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "no tiene :c",
        status: "activa",
        twitter: "https://twitter.com/Melty_witch",
        tiktok: "https://www.tiktok.com/@memelty",
        twitch: "https://www.twitch.tv/memelty",
        youtube: "https://www.youtube.com/channel/UCO3fm8W4IUxZ_EIlGh7IqFg",
        discord: "",
        types: ["Gamer", "Karaoke"]),
    Vtuber(
        name: "Triuwu",
        birthday: "Sept. 8",
        debut: "Febr. 13",
        country: "Panamá",
        emotes: [],
        sounds: [],
        colors: [Color(0xffEBFF00), Color.fromARGB(20, 246, 248, 102)],
        wallpapers: [
          "https://res.cloudinary.com/dyczsw1l2/image/upload/v1662782947/wallpapers/tri/wallpaper1_zn58ik.png"
        ],
        lore:
            "Muy buenas! soy una pequeña artista nacida en un hermoso y utópico lugar llamado Latinoamérica, en Panamá para ser más precisos. Me gustan las monas chinas y simpeo profesionalmente otras vtubers xDDDD Mi trabajo no será la gran cosa, pero es honesto y lo hago con cariño, asi que espero que les guste las pendejadas que haga uwu",
        image: "assets/images/tri.png",
        nameVtuber: "Memelty",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "no tiene :c",
        status: "activa",
        twitter: "https://twitter.com/Melty_witch",
        tiktok: "https://www.tiktok.com/@memelty",
        twitch: "https://www.twitch.tv/memelty",
        youtube: "https://www.youtube.com/channel/UCO3fm8W4IUxZ_EIlGh7IqFg",
        discord: "",
        types: ["Dibujante"]),
    Vtuber(
        name: "Chiimuu",
        birthday: "?",
        debut: "¿",
        country: "ChiimuuLandia",
        emotes: [],
        sounds: [],
        colors: [Color(0xffFF0000), Color.fromARGB(20, 148, 40, 40)],
        wallpapers: [],
        lore:
            "Buenas! puedes decirme chimu, chumi, mich- así no era. Mi vida es un chiste Y NO SOY GATA!!1! créanme xfa.",
        image: "assets/images/chomo.png",
        nameVtuber: "Memelty",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "",
        status: "activa",
        twitter: "",
        tiktok: "",
        twitch: "",
        youtube: "",
        discord: "",
        types: ["Dibujante"]),
    Vtuber(
        name: "Kotone",
        birthday: "Jul. 15",
        debut: "Nov. 15",
        country: "Chile",
        emotes: [],
        sounds: [],
        colors: [Color(0xffE3E2ED), Color.fromARGB(20, 160, 160, 166)],
        wallpapers: [
          "https://res.cloudinary.com/dyczsw1l2/image/upload/v1662798633/wallpapers/kotone/kotone1_cbs1by.png"
        ],
        lore:
            "Kotone who? Yo solo conozco a Potone, la joven promesa del vtubing hispano ᏊºัꈊºัᏊ Solo soy una oveja mañosa con pezuñas afiladas así que pórtate bien~ Bienvenid@ al corral ♡!! 🐑",
        image: "assets/images/kotone.png",
        nameVtuber: "Memelty",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "",
        status: "activa",
        twitter: "",
        tiktok: "",
        twitch: "",
        youtube: "",
        discord: "",
        types: ["Dibujante", "Vsinger", "Gamer"]),
    Vtuber(
        name: "Chocomint",
        birthday: "Jul. 15",
        debut: "Nov. 15",
        country: "Chile",
        emotes: [
          "assets/emotes/chocomint/menta1.png",
          "assets/emotes/chocomint/menta2.png",
          "assets/emotes/chocomint/menta3.png",
          "assets/emotes/chocomint/menta4.png",
          "assets/emotes/chocomint/menta5.png"
        ],
        sounds: [],
        colors: [Color(0xffB2C98D), Color.fromARGB(20, 181, 225, 174)],
        wallpapers: [],
        lore:
            "Hola! Soy Mint, puedes llamarme Minty, Choco, Chocomint y Menta. Soy una ninfa de menta que se aburrió de su trabajo y decidió que es mejor jugar en el pc jajaja.",
        image: "assets/images/menta.png",
        nameVtuber: "Memelty",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "",
        status: "activa",
        twitter: "",
        tiktok: "",
        twitch: "",
        youtube: "",
        discord: "",
        types: ["Dibujante", "Gamer"]),
    Vtuber(
        name: "NariVT",
        birthday: "Jun. 15",
        debut: "Febr. 7",
        country: "Chile",
        emotes: [
          "assets/emotes/narivt/Emote1.png",
          "assets/emotes/narivt/Emote2.png",
          "assets/emotes/narivt/Emote3.png",
          "assets/emotes/narivt/Emote4.png",
          "assets/emotes/narivt/Emote5.png",
        ],
        sounds: ["assets/sounds/melty/puto.mp3"],
        colors: [Color(0xff2596be), Color.fromARGB(19, 75, 70, 223)],
        wallpapers: [],
        lore:
            "Hola chicos! Soy nueva en este mundo Vtuber~ Soy Nari, una torpe Ajolote, WAIFUY HUSBANDO que le gusta jugar juegos y stremear!",
        image: "assets/images/narivt.png",
        nameVtuber: "Memelty",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "",
        status: "activa",
        twitter: "",
        tiktok: "",
        twitch: "",
        youtube: "",
        discord: "",
        types: ["Dibujante"]),
    Vtuber(
        name: "Ryudon",
        birthday: "Mayo. 23",
        debut: "Febr. 11",
        country: "Chile",
        emotes: [
          "assets/emotes/ryudon/ryudon1.png",
          "assets/emotes/ryudon/ryudon2.png",
          "assets/emotes/ryudon/ryudon3.gif",
          "assets/emotes/ryudon/ryudon4.gif",
          "assets/emotes/ryudon/ryudon5.gif",
        ],
        sounds: ["assets/sounds/melty/puto.mp3"],
        colors: [Color(0xff2B20AE), Color.fromARGB(20, 44, 32, 174)],
        wallpapers: [],
        lore:
            "Soy un simple humano, sin embargo, esta es mi 9na vida, cada vez que he muerto en mis anteriores 8 vidas lo he hecho con arrepentimientos en las decisiones que tomé, y por alguna razón, tras morir he vuelto a cuando tenía 11 años con todos los recuerdos de mis últimas vidas. En cada vida he tomado distintas decisiones, sin embargo, estoy un poco cansado y he decidido que en esta nueva oportunidad solo me dedicaré a hacer las cosas que me gustan, lo que me hace preguntar… ¿Ser VTuber será mi última mala decisión?",
        image: "assets/images/ryudon.png",
        nameVtuber: "Ryudon",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "",
        status: "activa",
        twitter: "",
        tiktok: "",
        twitch: "",
        youtube: "",
        discord: "",
        types: ["Musico", "Gamer"]),
    Vtuber(
        name: "Slachu",
        birthday: "??",
        debut: "??",
        country: "Chile",
        emotes: [
          "assets/emotes/slachu/Slachu1.png",
          "assets/emotes/slachu/Slachu2.png",
          "assets/emotes/slachu/Slachu3.png",
          "assets/emotes/slachu/Slachu4.png",
          "assets/emotes/slachu/Slachu5.png",
        ],
        sounds: ["assets/sounds/melty/puto.mp3"],
        colors: [Color(0xffBB311E), Color.fromARGB(20, 187, 48, 30)],
        wallpapers: [],
        lore:
            "Holaaa! me llamo Slachu Kawauso, y soy una nutria que se convirtió en yokai 🦦 me gusta jugar, cantar y dibujar. Espero que pasemos un buen rato juntos ❤",
        image: "assets/images/slachu.png",
        nameVtuber: "Froxe",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "",
        status: "activa",
        twitter: "",
        tiktok: "",
        twitch: "",
        youtube: "",
        discord: "",
        types: ["Vsinger", "Gamer"]),
    Vtuber(
        name: "Froxe",
        birthday: "Ene. 7",
        debut: "Ene. 7",
        country: "EE.UU",
        emotes: [
          "assets/emotes/froxe/1.png",
          "assets/emotes/froxe/2.png",
          "assets/emotes/froxe/3.png",
          "assets/emotes/froxe/4.png",
          "assets/emotes/froxe/5.png",
        ],
        sounds: ["assets/sounds/melty/puto.mp3"],
        colors: [Color(0xffF4FF3B), Color.fromARGB(19, 95, 221, 21)],
        wallpapers: [],
        lore:
            "Hola chicos! Soy nueva en este mundo Vtuber~ Soy Nari, una torpe Ajolote, WAIFUY HUSBANDO que le gusta jugar juegos y stremear!",
        image: "assets/images/froxe.png",
        nameVtuber: "Froxe",
        nicknames: "Melty, mona china, vtubo, tutubo",
        age: "< 100",
        live2d: "Idol Mikii",
        rigger: "Kibu_chan",
        accesories: "assets web",
        afiliation: "YandereLive",
        favoriteAnimal: "Perro",
        favoriteColor: "Rosado",
        favoriteFood: "Papas fritas",
        gender: "Femenino",
        height: "150cm (sin gorro) / 180cm (con gorro)",
        hobbies: "Videojuegos,ver series,Dibujar,ver anime,streaming",
        model3d: "",
        status: "activa",
        twitter: "",
        tiktok: "",
        twitch: "",
        youtube: "",
        discord: "",
        types: ["Vsinger", "Gamer"])
  ];

  List<Vtuber> get vtuberList {
    return [...vtubers];
  }

  Vtuber findByID(String name) {
    return vtubers.firstWhere((v) => v.name == name);
  }
}
